package cr.ac.una.prograIV.aerolineaUNA.domain;
// Generated 24/04/2017 03:51:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asiento generated by hbm2java
 */
public class Asiento  implements java.io.Serializable {


     private String idAsiento;
     private String letraFila;
     private int numeroFila;
     private String clase;
     private boolean estado;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Asiento() {
    }

	
    public Asiento(String idAsiento, String letraFila, int numeroFila, String clase, boolean estado) {
        this.idAsiento = idAsiento;
        this.letraFila = letraFila;
        this.numeroFila = numeroFila;
        this.clase = clase;
        this.estado = estado;
    }
    public Asiento(String idAsiento, String letraFila, int numeroFila, String clase, boolean estado, Set<Reserva> reservas) {
       this.idAsiento = idAsiento;
       this.letraFila = letraFila;
       this.numeroFila = numeroFila;
       this.clase = clase;
       this.estado = estado;
       this.reservas = reservas;
    }
   
    public String getIdAsiento() {
        return this.idAsiento;
    }
    
    public void setIdAsiento(String idAsiento) {
        this.idAsiento = idAsiento;
    }
    public String getLetraFila() {
        return this.letraFila;
    }
    
    public void setLetraFila(String letraFila) {
        this.letraFila = letraFila;
    }
    public int getNumeroFila() {
        return this.numeroFila;
    }
    
    public void setNumeroFila(int numeroFila) {
        this.numeroFila = numeroFila;
    }
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


