package cr.ac.una.prograIV.aerolineaUNA.domain;
// Generated 24/04/2017 03:51:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipaje generated by hbm2java
 */
public class Equipaje  implements java.io.Serializable {


     private int idEquipaje;
     private float kilos;
     private String nombre;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Equipaje() {
    }

	
    public Equipaje(int idEquipaje, float kilos) {
        this.idEquipaje = idEquipaje;
        this.kilos = kilos;
    }
    public Equipaje(int idEquipaje, float kilos, String nombre, Set<Reserva> reservas) {
       this.idEquipaje = idEquipaje;
       this.kilos = kilos;
       this.nombre = nombre;
       this.reservas = reservas;
    }
   
    public int getIdEquipaje() {
        return this.idEquipaje;
    }
    
    public void setIdEquipaje(int idEquipaje) {
        this.idEquipaje = idEquipaje;
    }
    public float getKilos() {
        return this.kilos;
    }
    
    public void setKilos(float kilos) {
        this.kilos = kilos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


