package cr.ac.una.prograIV.aerolineaUNA.domain;
// Generated 24/04/2017 03:51:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idPago;
     private float tipoCambio;
     private String moneda;
     private String medioPago;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Pago() {
    }

	
    public Pago(int idPago, float tipoCambio, String moneda, String medioPago) {
        this.idPago = idPago;
        this.tipoCambio = tipoCambio;
        this.moneda = moneda;
        this.medioPago = medioPago;
    }
    public Pago(int idPago, float tipoCambio, String moneda, String medioPago, Set<Reserva> reservas) {
       this.idPago = idPago;
       this.tipoCambio = tipoCambio;
       this.moneda = moneda;
       this.medioPago = medioPago;
       this.reservas = reservas;
    }
   
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
    public float getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(float tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public String getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


