package cr.ac.una.prograIV.aerolineaUNA.domain;
// Generated 24/04/2017 03:51:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int idReserva;
     private Asiento asiento;
     private Equipaje equipaje;
     private Pago pago;
     private Usuario usuario;
     private String observaciones;
     private Set<Vuelo> vuelos = new HashSet<Vuelo>(0);

    public Reserva() {
    }

	
    public Reserva(int idReserva, Asiento asiento, Equipaje equipaje, Pago pago, Usuario usuario, String observaciones) {
        this.idReserva = idReserva;
        this.asiento = asiento;
        this.equipaje = equipaje;
        this.pago = pago;
        this.usuario = usuario;
        this.observaciones = observaciones;
    }
    public Reserva(int idReserva, Asiento asiento, Equipaje equipaje, Pago pago, Usuario usuario, String observaciones, Set<Vuelo> vuelos) {
       this.idReserva = idReserva;
       this.asiento = asiento;
       this.equipaje = equipaje;
       this.pago = pago;
       this.usuario = usuario;
       this.observaciones = observaciones;
       this.vuelos = vuelos;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public Asiento getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(Asiento asiento) {
        this.asiento = asiento;
    }
    public Equipaje getEquipaje() {
        return this.equipaje;
    }
    
    public void setEquipaje(Equipaje equipaje) {
        this.equipaje = equipaje;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }




}


