package cr.ac.una.prograIV.aerolineaUNA.domain;
// Generated 24/04/2017 03:51:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private String idRuta;
     private Avion avion;
     private Horario horario;
     private String origen;
     private String destino;
     private float costo;
     private int horas;
     private int minutos;
     private List<Vuelo> vuelos;

    public Ruta() {
    }

	
    public Ruta(String idRuta, Avion avion, Horario horario, String origen, String destino, float costo,int horas,int minutos) {
        this.idRuta = idRuta;
        this.avion = avion;
        this.horario = horario;
        this.origen = origen;
        this.destino = destino;
        this.costo = costo;
        this.horas = horas;
        this.minutos = minutos;
    }
    public Ruta(String idRuta, Avion avion, Horario horario, String origen, String destino, float costo,int horas,int minutos,List<Vuelo> vuelos) {
       this.idRuta = idRuta;
       this.avion = avion;
       this.horario = horario;
       this.origen = origen;
       this.destino = destino;
       this.costo = costo;
       this.horas = horas;
       this.minutos = minutos;
       this.vuelos = vuelos;
    }
   
    public String getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(String idRuta) {
        this.idRuta = idRuta;
    }
    public Avion getAvion() {
        return this.avion;
    }
    
    public void setAvion(Avion avion) {
        this.avion = avion;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public float getCosto() {
        return this.costo;
    }
    
    public void setCosto(float costo) {
        this.costo = costo;
    }
     public int getHoras() {
        return this.horas;
    }
    
    public void setHoras(int horas) {
        this.horas = horas;
    }
     public int getMinutos() {
        return this.minutos;
    }
    
    public void setMinutos(int minutos) {
        this.minutos = minutos;
    }
    public List<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(List<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }




}


