package cr.ac.una.prograIV.aerolineaUNA.domain;
// Generated 24/04/2017 03:51:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private String contraseña;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String correo;
     private Date fechaNacimiento;
     private String direccion;
     private int telefonoLocal;
     private String telefonoCelular;
     private String tipo;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Usuario() {
    }

	
    public Usuario(String idUsuario, String contraseña, String nombre, String apellido1, String apellido2, String correo, Date fechaNacimiento, String direccion, int telefonoLocal, String telefonoCelular, String tipo) {
        this.idUsuario = idUsuario;
        this.contraseña = contraseña;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.correo = correo;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
        this.telefonoLocal = telefonoLocal;
        this.telefonoCelular = telefonoCelular;
        this.tipo = tipo;
    }
    public Usuario(String idUsuario, String contraseña, String nombre, String apellido1, String apellido2, String correo, Date fechaNacimiento, String direccion, int telefonoLocal, String telefonoCelular, String tipo, Set<Reserva> reservas) {
       this.idUsuario = idUsuario;
       this.contraseña = contraseña;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.correo = correo;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefonoLocal = telefonoLocal;
       this.telefonoCelular = telefonoCelular;
       this.tipo = tipo;
       this.reservas = reservas;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTelefonoLocal() {
        return this.telefonoLocal;
    }
    
    public void setTelefonoLocal(int telefonoLocal) {
        this.telefonoLocal = telefonoLocal;
    }
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


