package cr.ac.una.prograIV.aerolineaUNA.domain;
// Generated 24/04/2017 03:51:21 PM by Hibernate Tools 4.3.1



/**
 * Vuelo generated by hbm2java
 */
public class Vuelo  implements java.io.Serializable {


     private String idVuelo;
     private Reserva reserva;
     private Ruta ruta;

    public Vuelo() {
    }

    public Vuelo(String idVuelo, Reserva reserva, Ruta ruta) {
       this.idVuelo = idVuelo;
       this.reserva = reserva;
       this.ruta = ruta;
    }
   
    public String getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(String idVuelo) {
        this.idVuelo = idVuelo;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }




}


